### ISSUE TITLE
Problem with opening the program

### ISSUE THREAD

**Issue by AtomicError** [BrisklyDev/brisk#168]
Hi. I was eager to try this download manager and downloaded it but the problem is that the program does not open. Even when I run as administrator.
My operating system is Windows 11 23H2

**Comment by AminBhst** [comment]
Hey
Please check `C:\Users\USER\AppData\Roaming\com.aminbhst\Brisk\Brisk_logs.log` for any logs

**Comment by AtomicError** [comment]
Could the problem be with Flutter?

**Comment by AminBhst** [comment]
No I've never had an issue like this reported on windows before. Can't be related to flutter.
Could you delete the whole Brisk directory in the path I mentioned and try again?
Also check if there are other open instances of the app in the task manager.
You could also try the portable zip version as well.
Let me know how it goes and if it's still not working I'll send you a debug build so that we can check the logs in the terminal

**Comment by AminBhst** [comment]
I think there's probably something wrong on your system. Like failing to get the downloads direcory. I'll send you a debug release when I get home.
In the mean time please send me the content of the mentioned Brisk directory in a zip format

**Comment by AtomicError** [comment]
> I think there's probably something wrong on your system. Like failing to get the downloads direcory. I'll send you a debug release when I get home. In the mean time please send me the content of the mentioned Brisk directory in a zip format

[Brisk.zip](https://github.com/user-attachments/files/21581752/Brisk.zip)

**Comment by AminBhst** [comment]
I fixed the logger. Please download it from [here](https://github.com/AminBhst/brisk-dev/releases/tag/v2.3.7) and run the program and check the log file again.

**Comment by AminBhst** [comment]
I made a new build for you. Download it from [here](https://github.com/AminBhst/brisk-dev/releases/tag/v2.3.7). It will most likely fix your issue. There's something wrong with your Windows' notification service.

**Comment by AtomicError** [comment]
> I made a new build for you. Download it from [here](https://github.com/AminBhst/brisk-dev/releases/tag/v2.3.7). It will most likely fix your issue. There's something wrong with your Windows' notification service.

The program still won't open. I looked at the log. There was an error written in it. Just one line.
`Failed to initialize notification plugin!LateInitializationError: Field '_instance@105271368' has not been initialized.`

**Comment by AtomicError** [comment]
> If it was just this one line then honestly I have no clue what's wrong with your environment, because this error is now being ignored so the program can run despite this failure, and if there are no other errors, then technically the app should run without an issue. As a last ditch effort, I upgraded the flutter sdk and the notification plugin and completely removed notification initialization in the new build. You can download it from the same link I sent you. Preferably delete the Brisk directory before running the app.

Congratulations. To you. To me. It worked. The program opens.

<img width="1266" height="713" alt="Image" src="https://github.com/user-attachments/assets/07231a0d-9a46-47b4-8ea1-e94c299de5f9" />

I've been working with the app and wanted to share some feedback. Overall, the application has a great user interface and its performance is excellent. I also have a few suggestions that I hope you'll consider.

Download Hand-off: I noticed that when I click a download link on a website, the browser itself starts the download for a second or two before it stops and the file is passed to Brisk to handle. This was just an observation I wanted to report.

Popup Behavior: When I click a download link, instead of the full Brisk application window opening up with the download prompt, it would be much smoother if a small pop-up appeared directly on the web page I'm currently on, without bringing the main app to the front.

Online Video Downloader: I had an issue downloading an online video. The extension detected the video, but clicking the download button did nothing. I managed to fix this by changing the download engine to "Performance" in the settings. However, after I switched the engine, the app would crash most of the time when I clicked the "Start Download" button.

Video Download Button Visibility: The pop-up button that appears over online videos for downloading is inconsistent. Sometimes it appears, sometimes it's delayed, and other times it doesn't show up at all.

Thanks for developing a great app! I hope this feedback is helpful.

**Comment by AminBhst** [comment]
Glad it worked. About your points:
1- Yes that's by design. It's so that if brisk fails to download the file, the browser can download it without interruption.
2- Can't really do that. The plan is to support multiple windows in the future so that when you click on a link, a small window appears like it does with IDM. Unfortunately, flutter still hasn't supported the multi window feature but it will implemented in Brisk as soon as the flutter team ships this feature.
3- Downloading videos from the browser is quite complicated. Currently only m3u8 streams are supported. The video streaming download feature is planned to be expanded in the future but right now it's not a priority because I'm working on rewriting the download engine in rust.
4- The crash is weird. I think there are somethings really broken with your environment because as long as the rhttp.dll file is available, it should work. No idea there. Maybe a third party app like an antivirus or something is causing issues. Not sure. There are quite a lot of windows users but such issues have never been reported so it's definitely something with your local environment.
5- Many websites implement all sort of hacks and quirks that need to be accounted for. The download video button will not appear for unsupported streams.

Glad you like it. If you're planning to use the app from now on, the issues with your environment should be fixed. The build I sent you had changes that will never be up-streamed, meaning after updating the app someday, it will break again as these changes are missing in the official releases. If you only downloaded Brisk to test it and don't plan on using it in the long-run, I can close this issue now. If not, I can send you a couple of more builds to try to pinpoint the issues you're facing.

**Comment by AtomicError** [comment]
Yes, definitely. I’d really appreciate it if you could follow up on it. I want to work with it.

Also, some points I forgot to mention:
Why is it that when I exit the app, I can’t resume the download afterward?
And I wish there were options like pause, resume, and directional controls when right-clicking on a file in app.

**Comment by AtomicError** [comment]
And considering the issues I’m currently facing, how can I make use of the updates you release in the future?

**Comment by AminBhst** [comment]
> Yes, definitely. I’d really appreciate it if you could follow up on it. I want to work with it.
> 
> Also, some points I forgot to mention:
> Why is it that when I exit the app, I can’t resume the download afterward?
> And I wish there were options like pause, resume, and directional controls when right-clicking on a file in app.
> 

You can't resume the download? What happens when you resume it after restarting the app?

**Comment by AminBhst** [comment]
Also what do you mean by directional controls?
Sure I'll add pause and resume to right click menu for a future release.

**Comment by AminBhst** [comment]
> And considering the issues I’m currently facing, how can I make use of the updates you release in the future?

If we find the root cause then you can just update the app without issues.
I've released a new build in the same link as before. Test it and let me know if it's working or not.

**Comment by AtomicError** [comment]
> You can't resume the download? What happens when you resume it after restarting the app?

It seems like this issue only occurs when I use the performance engine. I switched back to the default engine, and everything is fine now — the app doesn’t even crash anymore.
However, one unfortunate thing about the default engine is that it can't download online videos — and that’s something I need on a daily basis. I genuinely rely on this feature. Could you please work on improving it?

**Comment by AminBhst** [comment]
> > You can't resume the download? What happens when you resume it after restarting the app?
> 
> It seems like this issue only occurs when I use the performance engine. I switched back to the default engine, and everything is fine now — the app doesn’t even crash anymore. However, one unfortunate thing about the default engine is that it can't download online videos — and that’s something I need on a daily basis. I genuinely rely on this feature. Could you please work on improving it?

That's weird. Both should work tbh. Could you send me an example link of a video stream that wasn't working with the default client? What I'm guessing is that maybe that website was restricted and you were using a system proxy and the default client was not using the system proxy properly. In that case, you can set proxy in the connection tab in settings. If you're using v2ray, set `127.0.0.1` as the address and the v2ray port as the proxy port.

**Comment by AtomicError** [comment]
The website is just a regular one — I don't think the content is intentionally restricted.
Their videos seem to be served via **M3U8** and **HLS** streams, although I'm not completely sure.
It's similar to platforms like dailymotion.com.

I randomly opened a video to test, and the app couldn’t download it.
In some cases, I waited so long that the app ended up crashing.
I didn’t see any logs, but I’m sending you this file anyway (note: it’s **not** from when the crash occurred — I was just testing, and fortunately it didn’t crash this time).

[Brisk.zip](https://github.com/user-attachments/files/21619989/Brisk.zip)

**Comment by AtomicError** [comment]
> That's weird. Both should work tbh. Could you send me an example link of a video stream that wasn't working with the default client? What I'm guessing is that maybe that website was restricted and you were using a system proxy and the default client was not using the system proxy properly. In that case, you can set proxy in the connection tab in settings. If you're using v2ray, set `127.0.0.1` as the address and the v2ray port as the proxy port.

No, I’m not using a proxy. I share my phone’s internet connection with my Windows PC, and the VPN is activated directly on the phone.

**Comment by AtomicError** [comment]
As for that test video, I was able to download it using the **FetchV** browser extension.
However, the link that FetchV found was different from the one the app detected for the same video — so maybe that’s where the problem lies.

**Comment by AminBhst** [comment]
> As for that test video, I was able to download it using the **FetchV** browser extension. However, the link that FetchV found was different from the one the app detected for the same video — so maybe that’s where the problem lies.

Doubt it. Downloads are done in separate threads so even if something breaks it shouldn't cause a crash. No clue tbh. I've never experienced a crash even once. It's pretty odd and the first time I'm seeing someone with this issue. It most definitely has something to do with your environment but I'm not sure what.
I'm closing this issue since most of the issues have been resolved for now. If you encountered another crash with a log other than the `Failed to initialize notification plugin!LateInitializationError: Field '_instance@105271368' has not been initialized.`, let me know and I'll reopen this issue.
